build:
    first-group:
        requires:
            - node: my-first-test
            - branch: /^master$|/^release-.+$/
    environment:
        php: '8.1.0'
        node: '14.0'

    tests:
        override:
            - true # disable test execution on scrutinizer

    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
