build:
    environment:
        php: '8.0.19'
        node: 18.16.0
        apt_packages:
            - glibc

    tests:
        override:
            - true # disable test execution on scrutinizer

    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
