build:
    environment:
        docker: true

    tests:
        override:
            - true # disable test execution on scrutinizer

    nodes:
        analysis:
            tests:
                override:
                    - docker run -v $PWD:/src -w /src node:18 js-scrutinizer-run
                    - docker run -v $PWD:/src -w /src php:8.0.19 php-scrutinizer-run
